simulate:
  fields:
    days:
      required: false
      selector:
        number:
          min: 1
          max: 365
          unit_of_measurement: days
          mode: box
create_dashboard:
  fields:
    url_path:
      required: false
      example: hasim-dashboard
      selector:
        text:
    title:
      required: false
      example: HASIM (editable)
      selector:
        text:
